project_id = "pgvfeolxgufldpwyheqf"

[functions.band-assistant]
verify_jwt = true

[functions.fetch-youtube]
verify_jwt = true

[functions.gmaps-key]
verify_jwt = false

[functions.send-rider]
verify_jwt = false

[functions.send-sms-reminders]
verify_jwt = false