project_id = "pgvfeolxgufldpwyheqf"

[functions.band-assistant]
verify_jwt = true

[functions.cleanup-past-events]
verify_jwt = false

[functions.fetch-youtube]
verify_jwt = true

[functions.gmaps-key]
verify_jwt = false

[functions.notify-availability-request]
verify_jwt = true

[functions.notify-gig-response]
verify_jwt = true

[functions.send-rider]
verify_jwt = false

[functions.send-sms-reminders]
verify_jwt = false

[functions.send-manager-sms]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false
